---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: cfbuildpacks/feature-eng-ci
    tag: cf

inputs:
- name: ci
- name: lock
- name: environments

outputs:
- name: space

run:
  path: ci/tasks/cf/create-space/task.sh

params:
  DOMAIN:
  ORG:
