---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: cfbuildpacks/feature-eng-ci
    tag: integration-cf

inputs:
  - name: ci
  - name: space
  - name: cnb2cf

run:
  path: ci/tasks/cnb2cf/integration/task.sh
