---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: cfbuildpacks/feature-eng-ci
    tag: go

inputs:
- name: ci
- name: feller

run:
  path: ci/tasks/feller/run/task.sh

params:
  TRACKER_PROJECT:
  TRACKER_TOKEN:
  GITHUB_TOKEN:
