---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: cfbuildpacks/feature-eng-ci
    tag: integration

inputs:
- name: ci
- name: buildpack

run:
  path: ci/tasks/cnb/integration/task.sh

params:
  GIT_TOKEN:
