---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cfbuildpacks/feature-eng-ci
    tag: go

inputs:
- name: ci
- name: repo

params:
  RUN_UNPRIVILEGED: false

run:
  path: ci/tasks/run-scripts-unit/run.sh
