---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: cfbuildpacks/feature-eng-ci
    tag: cf

inputs:
  - name: buildpacks-feature-eng-ci
  - name: release

params:
  GIT_TOKEN:

run:
  path: buildpacks-feature-eng-ci/tasks/cnb/dispatch/task.sh
