---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: cfbuildpacks/feature-eng-ci
    tag: minimal

inputs:
  - name: ci
  - name: release

params:
  GIT_TOKEN:

run:
  path: ci/tasks/cnb/dispatch/task.sh
