---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: cfbuildpacks/feature-eng-ci
    tag: minimal
inputs:
  - name: buildpacks-feature-eng-ci
  - name: release
params:
run:
  path: buildpacks-feature-eng-ci/tasks/cnb/dispatch/task.sh
  args: [release/version]
