---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: cfbuildpacks/feature-eng-ci
    tag: minimal

inputs:
- name: ci
- name: buildpack
- name: shimmed-buildpack
- name: version

outputs:
- name: artifacts

run:
  path: ci/tasks/metacnb/shim/prepare-release/task.sh

params:
  LANGUAGE:
  TRACKER_TOKEN:
  GITHUB_TOKEN:
