---
resources:
- name: ubuntu-image
  type: registry-image
  icon: docker
  source:
    repository: ubuntu
    tag: bionic

- name: minimal-image
  type: registry-image
  icon: docker
  source:
    repository: cfbuildpacks/feature-eng-ci
    tag: minimal
    username: ((dockerhub-account.username))
    password: ((dockerhub-account.password))

- name: minimal-dockerfile
  type: git
  icon: github
  source:
    uri: https://github.com/cloudfoundry/buildpack-feature-eng-ci
    branch: master
    paths:
    - dockerfiles/minimal.Dockerfile

jobs:
- name: build-minimal-image
  plan:
  - in_parallel:
    - get: ci
    - get: ubuntu-image
      trigger: true
    - get: minimal-dockerfile
      trigger: true
  - task: build
    file: ci/tasks/build-image/task.yml
    privileged: true
    params:
      CONTEXT: minimal-dockerfile/dockerfiles/minimal.Dockerfile
  - put: minimal-image
    params:
      image: image/image.tar
