resources:
- name: ci
  type: git
  icon: github-circle
  source:
    uri: https://github.com/cloudfoundry/buildpacks-feature-eng-ci
    branch: master

- name: cnb2cf
  type: git
  source:
    uri: git@github.com:cloudfoundry/cnb2cf.git
    branch: master
    private_key: ((cf-buildpacks-eng-github-ssh-key.private_key))

jobs:
- name: unit
  plan:
  - in_parallel:
    - get: ci
    - get: cnb2cf
      trigger: true
  - task: unit-tests
    file: ci/tasks/run-scripts-unit/task.yml
    params:
      RUN_UNPRIVILEGED: true
    input_mapping:
      repo: cnb2cf
