resources:
- name: ci
  type: git
  icon: github-circle
  source:
    uri: https://github.com/cloudfoundry/buildpacks-feature-eng-ci
    branch: master

- name: cnb2cf
  type: git
  icon: github-circle
  source:
    uri: git@github.com:cloudfoundry/cnb2cf.git
    branch: master
    private_key: ((cf-buildpacks-eng-github-ssh-key.private_key))

- name: lock
  type: pool
  icon: lock-open
  source:
    uri: git@github.com:cloudfoundry/public-buildpacks-ci-robots.git
    branch: master
    private_key: ((public-buildpacks-ci-robots-private-key.private_key))
    pool: edge-environments

- name: environments
  type: git
  icon: cloud-outline
  source:
    uri: git@github.com:cloudfoundry/buildpacks-envs.git
    branch: master
    private_key: ((buildpacks-envs-private-key.private_key))

jobs:
- name: unit
  plan:
  - in_parallel:
    - get: ci
    - get: cnb2cf
      trigger: true
  - task: unit-tests
    file: ci/tasks/cnb2cf/unit/task.yml

- name: integration
  plan:
  - in_parallel:
    - get: ci
    - get: environments
    - get: cnb2cf
      trigger: true
      passed:
      - unit
    - put: lock
      params:
        acquire: true
  - task: create-space
    file: ci/tasks/cf/create-space/task.yml
    params:
      DOMAIN: buildpacks-gcp.ci.cf-app.com
      ORG: pivotal
  - task: integration-tests
    file: ci/tasks/cnb2cf/integration/task.yml
  ensure:
    in_parallel:
      - task: delete-space
        file: ci/tasks/cf/delete-space/task.yml
      - put: lock
        params:
          release: lock
