---
resource_types:
- name: pcf-pool
  type: docker-image
  source:
    repository: cftoolsmiths/toolsmiths-envs-resource

resources:
- name: ci
  type: git
  icon: github-circle
  source:
    uri: https://github.com/cloudfoundry/buildpacks-feature-eng-ci
    branch: master

- name: cnb2cf
  type: git
  icon: github-circle
  source:
    uri: git@github.com:cloudfoundry/cnb2cf.git
    branch: master
    private_key: ((cf-buildpacks-eng-github-ssh-key.private_key))

- name: smith-environments-cf-deployment
  type: pcf-pool
  tags: [environments.toolsmiths.cf-app.com-shared-vsphere-worker]
  source:
    api_token: ((toolsmiths-api-token))
    hostname: environments.toolsmiths.cf-app.com
    pool_name: cf-deployment

jobs:
- name: unit
  plan:
  - in_parallel:
    - get: ci
    - get: cnb2cf
      trigger: true
  - task: unit-tests
    file: ci/tasks/cnb2cf/unit/task.yml

- name: integration
  plan:
  - in_parallel:
    - get: ci
    - get: cnb2cf
      trigger: true
      passed:
      - unit
    - put: smith-environments-cf-deployment
      tags: [environments.toolsmiths.cf-app.com-shared-vsphere-worker]
      params:
        action: claim
  - task: create-space
    file: ci/tasks/cf/create-space/task.yml
    input_mapping:
      lock: smith-environments-cf-deployment
    params:
      DOMAIN: cf-app.com
      ORG: pivotal
  - task: integration-tests
    file: ci/tasks/cnb2cf/integration/task.yml
  - put: smith-environments-cf-deployment
    tags: [environments.toolsmiths.cf-app.com-shared-vsphere-worker]
    params:
      action: unclaim
      env_file: smith-environments-cf-deployment/metadata
