---
resources:
- name: ci
  type: git
  icon: github-circle
  source:
    uri: https://github.com/cloudfoundry/buildpack-feature-eng-ci
    branch: master

- name: image
  type: registry-image
  icon: docker
  source:
    repository: gcr.io/cf-buildpacks/slack-delegate-bot
    username: _json_key
    password: ((gcp-service-account-key))

- name: configuration
  type: git
  icon: github-circle
  source:
    uri: https://github.com/cloudfoundry/buildpack-feature-eng-ci
    branch: master
    paths:
    - tasks/interrupt-bot/build*

jobs:
- name: build-and-push
  plan:
  - in_parallel:
    - get: ci
    - get: configuration
      trigger: true
  - task: build
    file: ci/tasks/build-image/task.yml
    privileged: true
    input_mapping:
      source: configuration
    params:
      CONTEXT: source/tasks/interrupt-bot/build
  - put: image
    params:
      image: image/image.tar

- name: deploy
  plan:
  - in_parallel:
    - get: ci
    - get: image
      passed: [build-and-push]
      trigger: true
  - task: deploy
    file: ci/tasks/interrupt-bot/deploy/task.yml
    params:
      SLACK_TOKEN: ((interrupt-bot-slack-token))
      PAIRIST_PASSWORD: ((pairist-account.password))
