---
resources:
- name: ci
  type: git
  icon: github-circle
  source:
    uri: https://github.com/cloudfoundry/buildpack-feature-eng-ci
    branch: master
    - tasks/slack-invitations/*
    - tasks/build-image/*

- name: image
  type: registry-image
  icon: docker
  source:
    repository: gcr.io/cf-buildpacks/slack-invitations
    username: _json_key
    password: ((cloud-runner-service-account-key))

jobs:
- name: build-and-push
  plan:
  - in_parallel:
    - get: ci
    - get: source
      trigger: true
  - task: build
    file: ci/tasks/build-image/task.yml
    privileged: true
    input_mapping:
      source: ci
    params:
      CONTEXT: source/tasks/slack-invitations/build
  - put: image
    params:
      image: image/image.tar

- name: deploy
  plan:
  - in_parallel:
    - get: ci
    - get: image
      passed: [build-and-push]
      trigger: true
  - task: deploy
    file: ci/tasks/slack-invitations/deploy/task.yml
    params:
      SERVICE_ACCOUNT_KEY: ((cloud-runner-service-account-key))
      INVITE_URL: ((slack-invite-url))
