---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: cfbuildpacks/feature-eng-ci
    tag: gcloud

inputs:
- name: ci

params:
  INVITE_URL:
  SERVICE_ACCOUNT_KEY:

run:
  path: ci/tasks/slack-invitations/deploy/run.sh
