---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: cfbuildpacks/feature-eng-ci
    tag: cf

inputs:
- name: ci
- name: space

run:
  path: ci/tasks/cf/delete-space/task.sh
