---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: cfbuildpacks/feature-eng-ci
    tag: go

inputs:
- name: ci
- name: cnb2cf

run:
  path: ci/tasks/cnb2cf/unit/task.sh
