#@ load("@ytt:data", "data")
#@yaml/text-templated-strings

resources:
- name: buildpack
  type: git
  icon: github-circle
  source:
    uri: "git@github.com:cloudfoundry/(@= data.values.buildpack @)-cnb.git"
    private_key: ((cf-buildpacks-eng-github-ssh-key.private_key))
    branch: master

- name: ci
  type: git
  icon: github-circle
  source:
    uri: https://github.com/cloudfoundry/buildpacks-feature-eng-ci
    branch: master
    paths:
    - tasks/cnb/*
    - util/*

- name: version
  type: semver
  icon: tag
  source:
    initial_version: 0.0.0
    driver: gcs
    bucket: artifacts.cf-buildpacks.appspot.com
    key: "cnb-versions/(@= data.values.buildpack @)-version"
    json_key: ((gcp-service-account-key))

- name: release
  type: github-release
  icon: package-variant-closed
  source:
    repository: "(@= data.values.buildpack @)-cnb"
    user: cloudfoundry
    access_token: ((buildpacks-github-token))

jobs:
- name: unit-tests
  public: true
  serial: true
  plan:
  - in_parallel:
    - get: ci
    - get: buildpack
      trigger: true
  - task: unit-tests
    file: ci/tasks/cnb/unit/task.yml

- name: integration-tests
  public: true
  serial: true
  plan:
  - in_parallel:
    - get: ci
    - get: buildpack
      trigger: true
      passed:
      - unit-tests
  - task: integration-tests
    file: ci/tasks/cnb/integration/task.yml
    privileged: true
    params:
      GIT_TOKEN: ((buildpacks-github-token))

- name: release
  public: true
  serial: true
  plan:
  - in_parallel:
    - get: ci
    - get: version
      params:
        bump: patch
    - get: buildpack
      trigger: true
      passed:
      - integration-tests
  - task: package
    file: ci/tasks/cnb/package/task.yml
    params:
      LANGUAGE: #@ data.values.buildpack
  - in_parallel:
    - put: release
      params:
        body: artifacts/body
        name: artifacts/name
        tag: artifacts/tag
        globs:
          - artifacts/*.tgz
    - put: version
      params:
        file: version/version
