---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: cfbuildpacks/feature-eng-ci
    tag: buildpackage

inputs:
- name: ci
- name: buildpack

outputs:
- name: buildpackage

run:
  path: ci/tasks/buildpackage/create/run.sh
