---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: cfbuildpacks/feature-eng-ci
    tag: go

inputs:
- name: ci
- name: feller
- name: version

outputs:
- name: artifacts

run:
  path: ci/tasks/feller/package/task.sh
