#@ load("@ytt:data", "data")
#@yaml/text-templated-strings
---
resource_types:
- name: pcf-pool
  type: docker-image
  source:
    repository: cftoolsmiths/toolsmiths-envs-resource

resources:
- name: ci
  type: git
  icon: github-circle
  source:
    uri: https://github.com/cloudfoundry/buildpacks-feature-eng-ci
    branch: master
    paths:
    - tasks/cf
    - tasks/shim/*
    - util/*

- name: buildpack
  type: git
  icon: github-circle
  source:
    uri: "git@github.com:cloudfoundry/(@= data.values.buildpack @)-cnb.git"
    private_key: ((cf-buildpacks-eng-github-ssh-key.private_key))
    branch: master

- name: version
  type: semver
  icon: tag
  source:
    initial_version: 0.0.0
    driver: gcs
    bucket: artifacts.cf-buildpacks.appspot.com
    key: "cnb-versions/(@= data.values.buildpack @)-family-version"
    json_key: ((gcp-service-account-key))

- name: cnb2cf
  type: git
  icon: github-circle
  source:
    uri: https://github.com/cloudfoundry/cnb2cf
    branch: master

- name: shimmed-buildpack
  type: s3
  icon: file-code
  source:
    bucket: buildpack-release-candidates
    regexp: "shims/(@= data.values.buildpack @)/(@= data.values.buildpack @)-buildpack-v(\\d+\\.\\d+\\.\\d+-rc\\.\\d+).zip"
    access_key_id: ((pivotal-offline-buildpacks-s3-access-key))
    secret_access_key: ((pivotal-offline-buildpacks-s3-secret-key))

- name: buildpack-acceptance-tests
  type: git
  icon: github-circle
  source:
    uri: https://github.com/cloudfoundry/buildpack-acceptance-tests
    branch: master

- name: smith-environments-cf-deployment
  type: pcf-pool
  tags: [environments.toolsmiths.cf-app.com-shared-vsphere-worker]
  source:
    api_token: ((toolsmiths-api-token))
    hostname: environments.toolsmiths.cf-app.com
    pool_name: cf-deployment

- name: release
  type: github-release
  icon: package-variant-closed
  source:
    user: cloudfoundry
    repository: "(@= data.values.buildpack @)-cnb"
    access_token: ((buildpacks-github-token))

jobs:
- name: package-rc
  serial: true
  public: true
  plan:
  - in_parallel:
    - get: ci
    - get: version
      params:
        pre: rc
    - get: buildpack
      trigger: true
    - get: cnb2cf
  - task: package-shim
    file: ci/tasks/shim/package/task.yml
    params:
      LANGUAGE: #@ data.values.buildpack
  - put: shimmed-buildpack
    params:
      file: shimmed-buildpack/*.zip
  - put: version
    params:
      file: version/version

- name: test-rc
  serial: true
  public: true
  plan:
  - in_parallel:
    - get: ci
    - get: buildpack-acceptance-tests
    - get: version
      passed:
      - package-rc
    - get: buildpack
      passed:
      - package-rc
    - put: smith-environments-cf-deployment
      tags: [environments.toolsmiths.cf-app.com-shared-vsphere-worker]
      params:
        action: claim
    - get: shimmed-buildpack
      trigger: true
      passed:
      - package-rc
  - task: create-space
    file: ci/tasks/cf/create-space/task.yml
    input_mapping:
      lock: smith-environments-cf-deployment
    params:
      DOMAIN: cf-app.com
      ORG: pivotal
  - task: integration-tests
    file: ci/tasks/shim/integration/task.yml
    privileged: true
    params:
      LANGUAGE: #@ data.values.buildpack
      GIT_TOKEN: ((buildpacks-github-token))
  - put: smith-environments-cf-deployment
    tags: [environments.toolsmiths.cf-app.com-shared-vsphere-worker]
    params:
      action: unclaim
      env_file: smith-environments-cf-deployment/metadata

- name: release
  public: true
  serial: true
  plan:
  - in_parallel:
    - get: ci
    - get: version
      params:
        bump: final
      passed:
      - test-rc
    - get: buildpack
      passed:
      - test-rc
    - get: shimmed-buildpack
      passed:
      - test-rc
  - task: prepare
    file: ci/tasks/shim/prepare-release/task.yml
    params:
      LANGUAGE: #@ data.values.buildpack
  - put: release
    params:
      commitish: artifacts/commitish
      name: artifacts/name
      tag: artifacts/tag
      globs:
        - artifacts/*.zip
        - artifacts/*.SHA256SUM.txt
  - put: version
    params:
      bump: patch
