---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: cfbuildpacks/feature-eng-ci
    tag: go

inputs:
- name: ci
- name: packit
- name: version

outputs:
- name: artifacts

run:
  path: ci/tasks/packit/package/task.sh
